/** Design: UI oficial do Lago — índice técnico grafite, navegação horizontal, filtros discretos e ações azuis. */
import { Link } from "wouter";
import { ArrowLeft, ArrowUpRight, FileStack, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { coverageCounts, coverageDomains, type CoverageStatus } from "@/data/coverage";

const filters: Array<CoverageStatus | "Todos"> = ["Todos", "Em implementação", "Mapeado", "Planejado"];
function LagoMark() { return <span className="lago-mark" aria-hidden="true"><i /><b /></span>; }
function statusClass(status: CoverageStatus) { return status === "Em implementação" ? "border-blue-400/40 bg-blue-500/15 text-blue-200" : status === "Mapeado" ? "border-slate-500/40 bg-slate-400/10 text-slate-200" : "border-stone-500/40 bg-stone-400/10 text-stone-300"; }

export default function Coverage() {
  const [filter, setFilter] = useState<CoverageStatus | "Todos">("Todos");
  const [query, setQuery] = useState("");
  const visibleDomains = useMemo(() => { const normalized = query.trim().toLocaleLowerCase("pt-BR"); return coverageDomains.filter((domain) => (filter === "Todos" || domain.status === filter) && (!normalized || `${domain.title} ${domain.contractFocus} ${domain.scope}`.toLocaleLowerCase("pt-BR").includes(normalized))); }, [filter, query]);
  return <div className="min-h-screen bg-[#161a24] text-[#f7f8fb]">
    <header className="border-b border-[#2e3542] bg-[#161a24]"><div className="mx-auto flex min-h-[66px] max-w-[1280px] items-center gap-6 px-6"><Link href="/" className="lago-brand" aria-label="Lago 360º"><LagoMark /><strong className="text-white">Lago</strong></Link><span className="hidden font-mono text-[10px] tracking-[.08em] text-[#9da7b6] sm:inline">DOCUMENTATION</span><div className="ml-auto flex items-center gap-4"><Link href="/" className="text-[13px] text-[#aab2c0] hover:text-white">Início</Link><Link href="/coverage" className="rounded-md border border-[#397eda]/60 bg-[#28599c] px-3 py-2 text-[12px] font-semibold text-white">Cobertura 360º</Link></div></div></header>
    <main><section className="border-b border-[#2e3542]"><div className="mx-auto grid max-w-[1120px] grid-cols-[minmax(0,1.1fr)_minmax(260px,.7fr)] gap-12 px-6 py-18 max-[780px]:grid-cols-1"><div><Link href="/" className="inline-flex items-center gap-2 font-mono text-[10px] tracking-[.08em] text-[#9eabc0] hover:text-[#82b9ff]"><ArrowLeft size={14} />DOCUMENTAÇÃO LAGO</Link><p className="mt-10 font-mono text-[10px] tracking-[.1em] text-[#92a0b3]">LAGO 360º / MATRIZ DE COBERTURA</p><h1 className="mt-4 max-w-[650px] text-[clamp(42px,6vw,70px)] font-bold leading-[.97] tracking-[-.075em]">Visibilidade sobre cada domínio de billing.</h1></div><p className="self-end text-[16px] leading-[1.55] text-[#aab2c0]">O índice conecta evidência de contrato, guia, exemplo e próxima implementação. Os estados indicam a maturidade da cobertura, não a disponibilidade da API.</p></div></section>
    <section className="mx-auto max-w-[1120px] px-6 py-12"><div className="grid grid-cols-3 overflow-hidden rounded-lg border border-[#323a48] bg-[#1d2330] max-[560px]:grid-cols-1">{(["Em implementação", "Mapeado", "Planejado"] as CoverageStatus[]).map((status) => <div className="border-r border-[#323a48] px-6 py-5 last:border-r-0 max-[560px]:border-b max-[560px]:last:border-b-0" key={status}><span className="font-mono text-[10px] tracking-[.08em] text-[#9da7b6]">{status.toUpperCase()}</span><strong className="mt-3 block text-4xl tracking-[-.07em] text-white">{coverageCounts[status]}</strong><span className="mt-2 block text-[12px] text-[#aab2c0]">domínios neste estágio</span></div>)}</div></section>
    <section id="matriz" className="border-t border-[#2e3542] bg-[#1b202b]"><div className="mx-auto max-w-[1120px] px-6 py-16"><div className="grid grid-cols-[minmax(0,1fr)_290px] items-end gap-7 max-[760px]:grid-cols-1"><div><p className="font-mono text-[10px] tracking-[.1em] text-[#9da7b6]">ÍNDICE DE DOMÍNIOS</p><h2 className="mt-3 text-4xl font-bold tracking-[-.06em]">Encontre o próximo ponto de implementação.</h2></div><label className="grid min-h-10 grid-cols-[18px_minmax(0,1fr)] items-center gap-2 rounded-md border border-[#39414f] bg-[#1d2330] px-3 text-[#9da7b6]"><Search size={16} /><input className="min-w-0 border-0 bg-transparent text-[13px] text-white outline-none placeholder:text-[#7e899a]" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar domínio ou contrato" /></label></div><div className="mt-8 flex flex-wrap gap-2" role="tablist">{filters.map((item) => <button key={item} role="tab" aria-selected={filter === item} onClick={() => setFilter(item)} className={`min-h-8 rounded-md border px-3 text-[11px] ${filter === item ? "border-[#397eda] bg-[#28599c] text-white" : "border-[#3a4352] bg-transparent text-[#aab2c0]"}`}>{item}</button>)}</div><div className="mt-7 overflow-hidden rounded-lg border border-[#343c4a]">{visibleDomains.map((domain) => <article className="grid min-h-[116px] grid-cols-[48px_minmax(150px,.72fr)_minmax(220px,1.1fr)_minmax(150px,.72fr)_34px] items-center gap-5 border-b border-[#343c4a] bg-[#1a202b] px-4 py-5 last:border-b-0 even:bg-[#1e2530] max-[920px]:grid-cols-[42px_minmax(0,1fr)_34px]" key={domain.slug}><span className="grid h-8 w-8 place-items-center rounded-md border border-[#3c4758] bg-[#252d3a] font-mono text-[10px] text-[#b9c6d8]">{domain.order}</span><div><span className="font-mono text-[10px] tracking-[.07em] text-[#98a5b7]">{domain.flowStage.toUpperCase()}</span><h3 className="mt-1 text-[17px] font-bold tracking-[-.03em]">{domain.title}</h3><span className={`mt-3 inline-flex rounded border px-2 py-1 font-mono text-[9px] ${statusClass(domain.status)}`}>{domain.status}</span></div><p className="text-[13px] leading-[1.45] text-[#aab2c0] max-[920px]:col-start-2">{domain.contractFocus}</p><p className="font-mono text-[10px] leading-[1.5] text-[#9ca6b5] max-[920px]:col-start-2">PRÓXIMA AÇÃO · {domain.nextTask}</p><Link href={`/docs/${domain.slug}`} aria-label={`Abrir guia de ${domain.title}`} className="grid h-8 w-8 place-items-center rounded-md border border-[#477dbd] text-[#9ac5ff] hover:bg-[#28599c] hover:text-white"><ArrowUpRight size={16} /></Link></article>)}{!visibleDomains.length && <div className="py-12 text-center text-[14px] text-[#aab2c0]">Nenhum domínio corresponde ao filtro.</div>}</div></div></section></main>
    <footer className="border-t border-[#2e3542] px-6 py-8 text-center font-mono text-[10px] text-[#8f9bad]">LAGO 360º · OPENAPI · GUIA · SDK · TESTE · FONTE</footer>
  </div>;
}
